# name: CICD Pipeline
# run-name: ${{ github.actor }} is running the CICD pipeline for ${{ github.event.repository.name }}

name: Deploy Sphinx documentation to Pages

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
      - name: pip install
        run: pip install -r ./docs/requirements.txt
      - name: run sphinx
        run: make html
      - name: artifact generation
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/build/html
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to pages
        id: deployment
        uses: actions/deploy-pages@v4

      



